[book]
title = "Hacking"
authors = ["Your Name"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[preprocessor.pagetoc]
command = "mdbook-pagetoc"
renderer = ["html"]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/chirag-bhil/site"
additional-css = ["theme/pagetoc.css"]

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true

