name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - run: pip install mkdocs-material
      
      - run: mkdocs build
        working-directory: ./docs
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site
      
      - uses: actions/deploy-pages@v3
